namespace TrenchWarfare.Domain.Enums {
    public enum Nation {
        AustriaHungary = 0,
        Belgium = 1,
        Bulgaria = 2,
        China = 3,
        France = 4,
        Germany = 5,
        GreatBritain = 6,
        Greece = 7,
        Italy = 8,
        Japan = 9,
        Korea = 10,
        Mexico = 11,
        Mongolia = 12,
        Montenegro = 13,
        Romania = 14,
        Russia = 15,
        Serbia = 16,
        Turkey = 17,
        USA = 18,
        USNorth = 19,
        USSouth = 20,
    }
}